class EN {
  static const Map<String, String> english = {
    '_language': 'English',
    '_skip': 'Skip',
    '_next': 'Next',
    '_onboarding1': "Enjoy Kuwait’s NO.1 Radio Station ANY TIME, FROM ANYWHERE",
    '_onboarding2': 'CONTRIBUTE WITH IN-APP CALLS AND MESSAGES FOR FREE',
    '_onboarding3': 'KEEP UPDATED WITH LATEST SHOWS, NEWS AND PRESENTERS INFO',
    '_log_in_with_facebook': 'LOGIN WITH FACEBOOK',
    '_login_with_g_account': 'LOGIN WITH G ACCOUNT',
    '_your_phone_numper': 'your phone numper',
    '_create_account': 'CREATE ACCOUNT',
    '_login': 'Login',
    '_already_registred': 'Already Registred? ',
    '_or': 'Or',
    '_your_password': 'your password',
    '_forgot_password': 'Forgot Password',
    '_message': 'MESSAGE',
    '_call': 'CALL',
    '_live_stream': 'Live Stream',
    '_shows': 'Shows',
    '_presenters': 'Presenters',
    '_schedule': 'Schedule',
    '_gallary': 'Gallery',
    '_news': 'News',
    '_about': 'About',
    '_version': 'Version',
    '_contact_us': 'Contact Us',
    '_night_mode': 'Night Mode',
    '_log_out': 'Logout',
    '_saturday': 'Saturday',
    '_sunday': 'Sunday',
    '_monday': 'Monday',
    '_tuesday': 'Tuesday',
    '_wednesday': 'Wednesday',
    '_thursday': 'Thursday',
    '_friday': 'Friday',
    '_air_time': 'Air time',
    '_social_media': 'Social media',
    '_notify_me': 'Notify Me',
    '_my_shows': 'My Shows',
    '_find_me_on_social_media': 'Find me on social media',
    '_creat_password': 'Creat Password',
    '_confirm_password': 'confirm your password',
    '_save_password': 'SAVE PASSWORD',
    '_not_registred': 'Not Registerd? ',
    '_complet_your_profile': 'Complet your profile',
    '_first_name': 'firs name',
    '_last_name': 'last name',
    '_add_data': 'Add Data',
    '_message_send': 'SEND US A MESSAGE',
    '_verification': 'Verification',
    '_enter_the_4-diglt_code_sent_to_you_at': 'Enter the 4-digit code sent to you at',
    "_didn't_enter_the_number_correctly": "Didn't enter the number correctly",
    '_the_numper_is_not_crrect':'the numper is not crrect',
    '_the_member_is_confirmed':'The member is confirmed',
    '_resend':'Resend',
    '_verify':'VERIFY',
    '_reset_password':'Reset Password',
    '_new_password':'New Password',
    '_continue':'Continue',
    '_arapic':'Arapic',
    '_english':'English',
    '_update':'Update Data',
    '_notfy_Me':'NOTIFY ME',
    'q8_pulse_broadcasting':'Q8 pulse Broadcasting',
    '_send_Message':'pleas login without google or facebook',
    '_audio': 'Audio',
    '_video': 'Video',
    '_containue': 'CONTAINUE AS A GUEST',
    '_register_message':'Please register to use this feature.',
    '_register_button':'Register',
    '_cancel_button':'Cancel',
    '_about1':"FM 88.8 Kuwait Pulse is one of the most creative broadcasting co-operatives in Kuwait. Its mission is to enrich people's lives with programs that inform, entertain and educate. It reflects upon and solves social issues facing society in general and youth in particular. It stimulates audiences across a full range of subjects and issues in order to achieve positive outcomes which provide people with what they need.",
    '_about2':'FM 88.8 Kuwait Pulse picked a well experienced team in Broadcasts & Media Sector such as Presenters, management, and technicians, provided many programs in many areas, to professionally choose wide range of entertainment, cultural, sports...Etc. Programs in both Arabic and foreign languages, in addition to airing a mix of Arabic and international songs ',
    '_about3':'FM 88.8 Kuwait Pulse – a Kuwaiti Radio Station broadcasts live from 360 Mall straight throughout the week, it was launched officially on 10th November 2016',
    '_hello':'Send Your Message',
    '_record_message':'Record sent, thanks for your contribution.',
    '_ok_button':'Continue',

};
}
